### ISSUE TITLE
Resque Pool needs a pluggable callable loader

### ISSUE THREAD

**Issue by mattdbridges** [joshuaflanagan/qtrix#1]
- [x] Fork `resque-pool` to `PeopleAdmin/resque-pool`
- [ ] Creation of a config loader/config manager.
- [ ] Create a PR to `resque-pool` to have a "pluggable" or "callable" config loader.
- [ ] Change QueueManager "glue" code to use `resque-pool`'s pluggable config loader.
- [ ] ?? Provide config loader for `qtrix`? Maybe a gem called `qtrix-pool`?

**Comment by joshuaflanagan** [comment]
Resque Pool now has a pluggable config loader, as of https://github.com/nevans/resque-pool/pull/85
