### ISSUE TITLE
Handle stale configs/hosts not checking in

### ISSUE THREAD

**Issue by lwoodson** [joshuaflanagan/qtrix#10]
Currently we blow away the matrix controlling queue lists mapped to hosts whenever a configuration changes.  We need to also invalidate the matrix whenever a host goes offline.  To accomplish this, we need to:

- Track the last check in for each host/resque-pool instance.
- Blow away the matrix so that its re-generated whenever a host has not checked in for a time, say after 20 seconds.

**Comment by joshuaflanagan** [comment]
Fixed by #12
