### ISSUE TITLE
Transfer ownership of repo

### ISSUE THREAD

**Issue by joshuaflanagan** [joshuaflanagan/qtrix#18]
I would like to take over maintenance of the official qtrix repo. It does not appear to have changed since @lwoodson stopped working on it over a year ago. I am about to resume active development it would be much simpler if I owned the official repo ([I already own the gem](https://rubygems.org/gems/qtrix)).

The version that PeopleAdmin uses (used?) will always be available via RubyGems, so that should not be a concern. And of course there is nothing stopping you from keeping your own fork of the repo if you ever do need modifications that aren't in the official version.

Please follow the [instructions for transferring a repository](https://help.github.com/articles/transferring-a-repository/) to assign it to @joshuaflanagan.

**Comment by billeisenhauer** [comment]
+1 :point_left:

**Comment by rpond-pa** [comment]
@joshuaflanagan Check your twitter.  Seeing a conflict with your existing repo with the same name.

**Comment by joshuaflanagan** [comment]
Oh, of course. Thanks for the heads up. Deleted my fork of the repo.

**Comment by rpond-pa** [comment]
Alright Josh.  Try it again.  I think I got it transferred over to you.

**Comment by joshuaflanagan** [comment]
Thanks!

**Comment by billeisenhauer** [comment]
Cool of you, @rpond-pa, to do this.  Look forward to see what Josh et al does with this.

**Comment by rpond-pa** [comment]
No worries.  We're not actively developing against it.  Hopefully, I won't get the stink eye for doing this.  :P  :poop: :eyes:

**Comment by dfinninger** [comment]
:+1:

**Comment by lwoodson** [comment]
Can I start making feature requests now, @joshuaflanagan?  When is the java port going to be ready?
