### ISSUE TITLE
Proper locking

### ISSUE THREAD

**Issue by lwoodson** [joshuaflanagan/qtrix#9]
Currently we are not locking around data structures that are manipulated in a non-atomic way.  There are minimal downsides to this, when a configuration-set is changed we may have some workers that are misconfigured for 5 seconds.  Still, it would be best to handle this in a more proper way. 

- We need to get proper locking in place for qtrix operations.
- These should be at the facade level.  So any public operation of the Qtrix module should block until they can obtain a lock, then release it when they are done.
- Possible options include [this](http://redis.io/commands/setnx) or [this](https://github.com/dv/redis-semaphore)

**Comment by joshuaflanagan** [comment]
Fixed by #17
